import {useEffect, useMemo, useState, type ReactNode} from 'react'
import {useClient} from 'sanity'
import {useIntentLink} from 'sanity/router'
import styled from 'styled-components'
import {esmeraTokens as t} from '../../studio/esmeraTokens'
import {
  Card, CardHeader, CardSub, CardTitle, Chip, Chips, DetailPanel, Divider, Empty, Grid,
  Header, HeaderActions, IconTile, InfoGrid, InfoLabel, InfoValue, MaterialIcon, Page,
  Pill, PrimaryButton, RowMeta, RowTitle, SearchBox, SearchInput, SecondaryButton,
  SectionLabel, Shell, StatCard, StatGrid, StatLabel, StatTop, StatValue, Subtitle,
  Thumb, Timeline, TimelineItem, Title, Toolbar, dateBR, money, shortDate,
} from './StitchUI'

const API_VERSION='2026-07-30'
function IntentLink({type,id,children,className}:{type:string;id?:string;children:ReactNode;className?:string}){const link=useIntentLink({intent:id?'edit':'create',params:id?{id:id.replace(/^drafts\./,''),type}:{type}});return <a className={className} href={link.href} onClick={link.onClick}>{children}</a>}
const PrimaryIntent=styled(IntentLink)`display:inline-flex;min-height:40px;align-items:center;justify-content:center;gap:8px;border-radius:999px;background:${t.color.primary};color:${t.color.onPrimary};padding:0 18px;font-size:13px;font-weight:600;text-decoration:none;.material-symbols-outlined{font-size:19px}`
const SecondaryIntent=styled(IntentLink)`display:inline-flex;min-height:38px;align-items:center;justify-content:center;gap:7px;border:1px solid ${t.color.line};border-radius:8px;background:${t.color.surfaceLowest};color:${t.color.ink};padding:0 14px;font-size:13px;font-weight:600;text-decoration:none;&:hover{background:${t.color.surfaceLow}}`

const CustomerList=styled.div`display:grid;gap:8px;`
const CustomerItem=styled.button<{$selected?:boolean}>`display:flex;width:100%;min-height:82px;align-items:center;gap:12px;border:1px solid ${t.color.line};border-radius:12px;background:${({$selected})=>$selected?t.color.surfaceLow:t.color.surfaceLowest};padding:12px;text-align:left;cursor:pointer;&:hover{background:${t.color.surfaceLow}}`
const Initial=styled.div`display:grid;width:44px;height:44px;flex:0 0 44px;place-items:center;border-radius:50%;background:${t.color.primarySoft};color:${t.color.primary};font-family:${t.typography.headline};font-size:14px;font-weight:700;`
const CustomerLayout=styled.div`display:grid;grid-template-columns:minmax(260px,.65fr) minmax(0,1.35fr) minmax(290px,.62fr);gap:18px;align-items:start;@media(max-width:1200px){grid-template-columns:320px 1fr;> *:last-child{grid-column:1/-1}}@media(max-width:800px){grid-template-columns:1fr}`

type Customer={_id:string;name?:string;phone?:string;email?:string;city?:string;state?:string;preferences?:string[];tags?:string[];relationshipNotes?:string;salesCount?:number}
type SaleMini={_id:string;number?:string;status?:string;totalCents?:number;_createdAt?:string}
export function CustomersPage(){
 const client=useClient({apiVersion:API_VERSION});const[customers,setCustomers]=useState<Customer[]>([]);const[selected,setSelected]=useState('');const[q,setQ]=useState('');const[sales,setSales]=useState<SaleMini[]>([])
 useEffect(()=>{client.fetch<Customer[]>(`*[_type=="customer"]|order(_updatedAt desc){_id,name,phone,email,city,state,preferences,tags,relationshipNotes,"salesCount":count(*[_type=="sale"&&references(^._id)])}`).then(x=>{setCustomers(x);setSelected(s=>s||x[0]?._id||'')})},[client])
 useEffect(()=>{if(!selected){setSales([]);return}client.fetch<SaleMini[]>(`*[_type=="sale"&&customer._ref==$id]|order(_createdAt desc)[0...5]{_id,number,status,totalCents,_createdAt}`,{id:selected.replace(/^drafts\./,'')}).then(setSales)},[client,selected])
 const filtered=customers.filter(c=>`${c.name||''} ${c.phone||''} ${c.email||''} ${(c.tags||[]).join(' ')}`.toLowerCase().includes(q.toLowerCase()));const c=customers.find(x=>x._id===selected)||filtered[0]
 return <Page><Shell><Header><div><Title>Clientes</Title><Subtitle>Relacionamento, histórico e oportunidades em uma única tela.</Subtitle></div><PrimaryIntent type="customer"><MaterialIcon>person_add</MaterialIcon>Novo cliente</PrimaryIntent></Header><Toolbar><SearchBox><MaterialIcon>search</MaterialIcon><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome, telefone, e-mail ou tag..."/></SearchBox><Chips><Chip>{customers.length} contatos</Chip><Chip>{customers.reduce((a,x)=>a+(x.salesCount||0),0)} compras registradas</Chip></Chips></Toolbar>
 <CustomerLayout><Card><CardHeader><div><CardTitle>Clientes</CardTitle><CardSub>Cadastro e relacionamento</CardSub></div></CardHeader><CustomerList>{filtered.map(item=><CustomerItem key={item._id} $selected={item._id===c?._id} onClick={()=>setSelected(item._id)}><Initial>{(item.name||'ES').split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}</Initial><div style={{minWidth:0,flex:1}}><RowTitle>{item.name||'Cliente sem nome'}</RowTitle><RowMeta>{item.phone||item.email||'Sem contato'} · {item.salesCount||0} compras</RowMeta></div><Pill $tone={(item.salesCount||0)>0?'green':'blue'}>{(item.salesCount||0)>0?'Cliente':'Lead'}</Pill></CustomerItem>)}</CustomerList>{!filtered.length&&<Empty>Nenhum cliente encontrado.</Empty>}</Card>
 {c?<Card><CardHeader><div style={{display:'flex',alignItems:'center',gap:12}}><Initial style={{width:54,height:54,flexBasis:54}}>{(c.name||'ES').split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}</Initial><div><CardTitle>{c.name}</CardTitle><CardSub>{[c.city,c.state].filter(Boolean).join(' · ')||'Relacionamento Esméra'}</CardSub></div></div><SecondaryIntent type="customer" id={c._id}><MaterialIcon>edit</MaterialIcon>Editar</SecondaryIntent></CardHeader>
 <InfoGrid><div><InfoLabel>Telefone</InfoLabel><InfoValue>{c.phone||'—'}</InfoValue></div><div><InfoLabel>E-mail</InfoLabel><InfoValue>{c.email||'—'}</InfoValue></div><div><InfoLabel>Compras</InfoLabel><InfoValue>{c.salesCount||0}</InfoValue></div><div><InfoLabel>Perfil</InfoLabel><InfoValue>{(c.salesCount||0)>1?'Recorrente':(c.salesCount||0)?'Cliente':'Em qualificação'}</InfoValue></div></InfoGrid>
 <Divider/><SectionLabel>Interesse atual</SectionLabel><Chips>{(c.preferences||[]).length?(c.preferences||[]).map(x=><Chip key={x}>{x}</Chip>):<Chip>Sem preferências registradas</Chip>}</Chips><div style={{marginTop:14,color:t.color.textSecondary,fontSize:14,lineHeight:'20px'}}>{c.relationshipNotes||'Adicione notas de relacionamento para manter o contexto comercial.'}</div>
 <Divider/><CardTitle style={{fontSize:16}}>Histórico de vendas</CardTitle><Timeline style={{marginTop:16}}>{sales.length?sales.map(s=><TimelineItem key={s._id}><RowTitle>Venda #{s.number||'—'} · {money(s.totalCents)}</RowTitle><RowMeta>{dateBR(s._createdAt)} · {s.status||'status não definido'}</RowMeta></TimelineItem>):<TimelineItem><RowTitle>Nenhuma venda registrada</RowTitle><RowMeta>O histórico comercial aparecerá aqui.</RowMeta></TimelineItem>}</Timeline>
 </Card>:<Empty>Selecione um cliente.</Empty>}
 <DetailPanel><CardTitle style={{fontSize:17}}>Próxima Ação</CardTitle><Divider/><div style={{display:'flex',alignItems:'center',gap:12}}><IconTile><MaterialIcon>event</MaterialIcon></IconTile><div><InfoLabel>Relacionamento</InfoLabel><InfoValue>Retornar pelo WhatsApp</InfoValue></div></div><CardSub style={{marginTop:14}}>Use tarefas e leads para agendar o próximo contato e manter o histórico rastreável.</CardSub><div style={{marginTop:18}}><PrimaryIntent type="task"><MaterialIcon>add_task</MaterialIcon>Criar tarefa</PrimaryIntent></div><Divider/><CardTitle style={{fontSize:16}}>Atalhos Rápidos</CardTitle><Grid $cols={2} style={{gap:8,marginTop:12}}><SecondaryIntent type="sale"><MaterialIcon>attach_money</MaterialIcon>Venda</SecondaryIntent><SecondaryIntent type="task"><MaterialIcon>add_task</MaterialIcon>Tarefa</SecondaryIntent><SecondaryIntent type="lead"><MaterialIcon>person_add</MaterialIcon>Lead</SecondaryIntent><SecondaryIntent type="customer" id={c?._id}><MaterialIcon>sticky_note</MaterialIcon>Notas</SecondaryIntent></Grid></DetailPanel>
 </CustomerLayout></Shell></Page>
}

type Sale={_id:string;number?:string;status?:string;channel?:string;owner?:string;nextAction?:string;nextActionAt?:string;totalCents?:number;customer?:{_id?:string;name?:string};items?:{snapshotTitle?:string;snapshotSelection?:string;quantity?:number;unitPriceCents?:number;priceMode?:string}[];_createdAt?:string}
const statusLabel:Record<string,string>={draft:'Novo',proposal:'Proposta enviada',negotiation:'Negociação',confirmed:'Confirmada',production:'Em produção',ready:'Pronta entrega',delivered:'Ganho',cancelled:'Cancelada'}
const SalesLayout=styled.div`display:grid;grid-template-columns:minmax(300px,.78fr) minmax(0,1.22fr);gap:18px;align-items:start;@media(max-width:980px){grid-template-columns:1fr}`
const SaleItem=styled.button<{$selected?:boolean}>`display:block;width:100%;border:1px solid ${t.color.line};border-radius:12px;background:${({$selected})=>$selected?t.color.surfaceLow:t.color.surfaceLowest};padding:15px;text-align:left;cursor:pointer;&:hover{background:${t.color.surfaceLow}}`
const SaleList=styled.div`display:grid;gap:10px;`
const FunnelWrap=styled.div`display:grid;grid-template-columns:repeat(5,minmax(200px,1fr));gap:14px;overflow-x:auto;padding-bottom:10px;`
const FunnelColumn=styled.div`min-height:420px;border-radius:12px;background:${t.color.surfaceLow};padding:14px;`
export function SalesPage(){
 const client=useClient({apiVersion:API_VERSION});const[sales,setSales]=useState<Sale[]>([]);const[selected,setSelected]=useState('');const[q,setQ]=useState('');const[view,setView]=useState<'list'|'pipeline'>('list')
 useEffect(()=>{client.fetch<Sale[]>(`*[_type=="sale"]|order(_updatedAt desc){_id,number,status,channel,owner,nextAction,nextActionAt,totalCents,_createdAt,"customer":customer->{_id,name},items[]{snapshotTitle,snapshotSelection,quantity,unitPriceCents,priceMode}}`).then(x=>{setSales(x);setSelected(s=>s||x[0]?._id||'')})},[client])
 const filtered=sales.filter(s=>`${s.number||''} ${s.customer?.name||''} ${s.items?.[0]?.snapshotTitle||''}`.toLowerCase().includes(q.toLowerCase()));const s=sales.find(x=>x._id===selected)||filtered[0]
 const open=sales.filter(x=>!['delivered','cancelled'].includes(x.status||'')).length;const proposals=sales.filter(x=>x.status==='proposal').length;const waiting=sales.filter(x=>['proposal','negotiation'].includes(x.status||'')).length;const closed=sales.filter(x=>x.status==='delivered').length;const value=sales.filter(x=>!['delivered','cancelled'].includes(x.status||'')).reduce((a,x)=>a+(x.totalCents||0),0)
 return <Page><Shell><Header><div><Title>Vendas</Title><Subtitle>Negociações, pedidos e acompanhamento comercial.</Subtitle></div><PrimaryIntent type="sale"><MaterialIcon>add</MaterialIcon>Nova venda</PrimaryIntent></Header><StatGrid>
  {[['Em negociação',open,'+2','green','handshake'],['Propostas enviadas',proposals,'Estável','blue','description'],['Aguardando cliente',waiting,'Atenção','red','schedule'],['Vendas concluídas',closed,'Fechadas','green','check_circle']].map(([l,v,p,tone,icon])=><StatCard key={String(l)}><StatTop><IconTile $tone={tone==='blue'?'blue':tone==='red'?'red':'green'}><MaterialIcon>{icon}</MaterialIcon></IconTile><Pill $tone={tone as any}>{p}</Pill></StatTop><div><StatLabel>{l}</StatLabel><StatValue>{v}</StatValue></div></StatCard>)}</StatGrid>
 <Card style={{marginBottom:20,padding:'16px 20px'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><StatLabel>Valor em negociação</StatLabel><StatValue style={{fontSize:22}}>{money(value)}</StatValue></div><div style={{display:'flex',gap:8}}><SecondaryButton href="#" onClick={(e)=>{e.preventDefault();setView('list')}} style={view==='list'?{background:t.color.surfaceContainer}:undefined}><MaterialIcon>list</MaterialIcon>Listagem</SecondaryButton><SecondaryButton href="#" onClick={(e)=>{e.preventDefault();setView('pipeline')}} style={view==='pipeline'?{background:t.color.surfaceContainer}:undefined}><MaterialIcon>view_kanban</MaterialIcon>Pipeline</SecondaryButton></div></div></Card>
 {view==='pipeline'?<FunnelWrap>{[['draft','Novo'],['proposal','Proposta'],['negotiation','Negociação'],['confirmed','Confirmada'],['delivered','Ganho']].map(([key,label])=><FunnelColumn key={key}><CardHeader><CardTitle style={{fontSize:16}}>{label}</CardTitle><Pill>{sales.filter(x=>x.status===key).length}</Pill></CardHeader><SaleList>{sales.filter(x=>x.status===key).map(item=><SaleItem key={item._id} onClick={()=>{setSelected(item._id);setView('list')}}><Pill $tone="green">#{item.number}</Pill><RowTitle style={{marginTop:10}}>{item.customer?.name||'Sem cliente'}</RowTitle><RowMeta>{item.items?.[0]?.snapshotTitle||'Venda Esméra'}</RowMeta><div style={{marginTop:12,fontWeight:700}}>{money(item.totalCents)}</div></SaleItem>)}</SaleList></FunnelColumn>)}</FunnelWrap>:<><Toolbar><SearchBox><MaterialIcon>search</MaterialIcon><SearchInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar venda, cliente ou produto..."/></SearchBox><Chips><Chip>{sales.length} vendas</Chip><Chip>{open} abertas</Chip></Chips></Toolbar><SalesLayout>
   <Card><CardHeader><CardTitle style={{fontSize:17}}>Listagem</CardTitle><Pill>{filtered.length}</Pill></CardHeader><SaleList>{filtered.map(item=><SaleItem key={item._id} $selected={item._id===s?._id} onClick={()=>setSelected(item._id)}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><Pill $tone="blue">#{item.number||'—'}</Pill><Pill $tone={item.status==='delivered'?'green':item.status==='cancelled'?'red':'sand'}>{statusLabel[item.status||'']||item.status||'—'}</Pill></div><RowTitle style={{marginTop:10}}>{item.customer?.name||'Sem cliente'}</RowTitle><RowMeta>{item.items?.[0]?.snapshotTitle||'Venda Esméra'} · {item.channel||'canal não definido'}</RowMeta><div style={{marginTop:10,fontWeight:700}}>{money(item.totalCents)}</div></SaleItem>)}</SaleList></Card>
   {s?<DetailPanel><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><CardTitle>{s.customer?.name||'Venda sem cliente'}</CardTitle><CardSub>Venda #{s.number} • Aberta em {dateBR(s._createdAt)}</CardSub></div><Pill $tone={s.status==='delivered'?'green':s.status==='cancelled'?'red':'blue'}>{statusLabel[s.status||'']||s.status}</Pill></div><Divider/><InfoGrid><div><InfoLabel>Responsável</InfoLabel><InfoValue>{s.owner||'—'}</InfoValue></div><div><InfoLabel>Canal</InfoLabel><InfoValue>{s.channel||'—'}</InfoValue></div><div><InfoLabel>Total</InfoLabel><InfoValue>{money(s.totalCents)}</InfoValue></div><div><InfoLabel>Próxima ação</InfoLabel><InfoValue>{s.nextAction||'—'}</InfoValue></div></InfoGrid><Divider/><CardTitle style={{fontSize:16}}>Produtos Selecionados</CardTitle><div style={{display:'grid',gap:8,marginTop:12}}>{(s.items||[]).map((it,i)=><div key={i} style={{border:`1px solid ${t.color.line}`,borderRadius:10,padding:12}}><RowTitle>{it.snapshotTitle||'Produto'}</RowTitle><RowMeta>{it.snapshotSelection||'Sem seleção'} · {it.quantity||1} un.</RowMeta><div style={{marginTop:6,fontWeight:700}}>{it.priceMode==='inquiry'?'Sob consulta':money(it.unitPriceCents)}</div></div>)}</div><Divider/><CardTitle style={{fontSize:16}}>Status da Venda</CardTitle><Chips style={{marginTop:12}}>{['Novo','Curadoria','Proposta enviada','Aguardando pagamento','Ganho'].map((x,i)=><Chip key={x} style={i<=2?{borderColor:t.color.primary,color:t.color.primary}:undefined}>{x}</Chip>)}</Chips><Divider/><CardTitle style={{fontSize:16}}>Próxima Ação</CardTitle><CardSub>{s.nextAction||'Nenhuma ação agendada.'}</CardSub><InfoValue>{dateBR(s.nextActionAt)}</InfoValue><div style={{marginTop:18}}><SecondaryIntent type="sale" id={s._id}><MaterialIcon>edit</MaterialIcon>Editar venda</SecondaryIntent></div></DetailPanel>:<Empty>Selecione uma venda.</Empty>}
  </SalesLayout></>}
 </Shell></Page>
}

type AfterSale={_id:string;status?:string;priority?:string;owner?:string;expectedDeliveryAt?:string;deliveredAt?:string;deliveryNotes?:string;incidentType?:string;incidentDetails?:string;resolution?:string;customer?:{name?:string};sale?:{number?:string;totalCents?:number};followUps?:{moment?:string;dueAt?:string;purpose?:string;status?:string;notes?:string}[]}
const AfterLayout=styled.div`display:grid;grid-template-columns:minmax(0,1fr) minmax(340px,.72fr);gap:20px;align-items:start;@media(max-width:1000px){grid-template-columns:1fr}`
const QueueItem=styled.button<{$selected?:boolean}>`display:grid;grid-template-columns:92px minmax(0,1fr) auto;gap:14px;align-items:center;width:100%;min-height:78px;border:0;border-bottom:1px solid ${t.color.line};background:${({$selected})=>$selected?t.color.surfaceLow:'transparent'};padding:12px 8px;text-align:left;cursor:pointer;&:hover{background:${t.color.surfaceLow}}@media(max-width:600px){grid-template-columns:70px 1fr}`
export function AfterSalesPage(){
 const client=useClient({apiVersion:API_VERSION});const[data,setData]=useState<AfterSale[]>([]);const[selected,setSelected]=useState('')
 useEffect(()=>{client.fetch<AfterSale[]>(`*[_type=="afterSale"]|order(_updatedAt desc){_id,status,priority,owner,expectedDeliveryAt,deliveredAt,deliveryNotes,incidentType,incidentDetails,resolution,"customer":customer->{name},"sale":sale->{number,totalCents},followUps[]{moment,dueAt,purpose,status,notes}}`).then(x=>{setData(x);setSelected(s=>s||x[0]?._id||'')})},[client]);const a=data.find(x=>x._id===selected)||data[0];const followups=data.flatMap(x=>x.followUps||[]);const today=new Date();const todayCount=followups.filter(f=>f.status==='pending'&&f.dueAt&&new Date(f.dueAt).toDateString()===today.toDateString()).length;const overdue=followups.filter(f=>f.status==='pending'&&f.dueAt&&new Date(f.dueAt)<today).length;const incidents=data.filter(x=>x.incidentType&&x.incidentType!=='none'&&!['resolved','closed'].includes(x.status||'')).length;const deliveries=data.filter(x=>!x.deliveredAt&&!['resolved','closed'].includes(x.status||'')).length
 return <Page><Shell><Header><div><Title>Pós-venda</Title><Subtitle>Acompanhe entregas, follow-ups e ocorrências em tempo real.</Subtitle></div><HeaderActions><PrimaryIntent type="afterSale"><MaterialIcon>add_task</MaterialIcon>Novo Follow-up</PrimaryIntent><SecondaryButton href="#"><MaterialIcon>file_download</MaterialIcon>Exportar Relatório</SecondaryButton></HeaderActions></Header><StatGrid>
  {[['Follow-ups hoje',todayCount,'green','event_repeat'],['Atrasados',overdue,'red','warning'],['Ocorrências abertas',incidents,'red','assignment_late'],['Entregas em acompanhamento',deliveries,'blue','local_shipping']].map(([l,v,tone,icon])=><StatCard key={String(l)}><StatTop><IconTile $tone={tone==='red'?'red':tone==='blue'?'blue':'green'}><MaterialIcon>{icon}</MaterialIcon></IconTile><Pill $tone={tone as any}>{tone==='red'?'Ação requerida':'Operacional'}</Pill></StatTop><div><StatLabel>{l}</StatLabel><StatValue>{v}</StatValue></div></StatCard>)}</StatGrid><AfterLayout>
  <Card><CardHeader><CardTitle>Fila Operacional</CardTitle><Chips><Chip><MaterialIcon>calendar_today</MaterialIcon>Prazo</Chip><Chip><MaterialIcon>priority_high</MaterialIcon>Prioridade</Chip></Chips></CardHeader>{data.length?data.map(item=>{const next=(item.followUps||[]).filter(f=>f.status==='pending').sort((x,y)=>String(x.dueAt).localeCompare(String(y.dueAt)))[0];return <QueueItem key={item._id} $selected={item._id===a?._id} onClick={()=>setSelected(item._id)}><div><SectionLabel style={{margin:0}}>{next?.dueAt?shortDate(next.dueAt):'Hoje'}</SectionLabel><Pill $tone="blue">{next?.moment?.toUpperCase()||'Acompanh.'}</Pill></div><div><RowTitle>{item.customer?.name||'Cliente'}</RowTitle><RowMeta>{next?.purpose||'Acompanhamento pós-venda'} · Venda #{item.sale?.number||'—'}</RowMeta></div><Pill $tone={['high','urgent'].includes(item.priority||'')?'red':'neutral'}>{item.priority==='urgent'?'Urgente':item.priority==='high'?'Alta':'Normal'}</Pill></QueueItem>}):<Empty>Nenhum acompanhamento cadastrado.</Empty>}</Card>
  {a?<DetailPanel><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><Pill $tone="blue">Em Acompanhamento</Pill><CardTitle style={{marginTop:10}}>{a.customer?.name||'Cliente'}</CardTitle><CardSub>Venda #{a.sale?.number||'—'}</CardSub></div><SecondaryIntent type="afterSale" id={a._id}><MaterialIcon>edit</MaterialIcon></SecondaryIntent></div><Divider/><InfoGrid><div><InfoLabel>Entrega prevista</InfoLabel><InfoValue>{dateBR(a.expectedDeliveryAt)}</InfoValue></div><div><InfoLabel>Entrega realizada</InfoLabel><InfoValue>{dateBR(a.deliveredAt)}</InfoValue></div><div><InfoLabel>Valor</InfoLabel><InfoValue>{money(a.sale?.totalCents)}</InfoValue></div><div><InfoLabel>Responsável</InfoLabel><InfoValue>{a.owner||'—'}</InfoValue></div></InfoGrid><Divider/><CardTitle style={{fontSize:16}}>Acompanhamento</CardTitle><Timeline style={{marginTop:14}}>{(a.followUps||[]).length?(a.followUps||[]).map((f,i)=><TimelineItem key={i}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><RowTitle>{f.moment?.toUpperCase()}: {f.purpose||'Follow-up'}</RowTitle><Pill $tone={f.status==='done'?'green':f.status==='pending'?'sand':'neutral'}>{f.status==='done'?'Feito':f.status==='pending'?'Pendente':'Cancelado'}</Pill></div><RowMeta>{dateBR(f.dueAt)} · {f.notes||'Sem observações'}</RowMeta></TimelineItem>):<TimelineItem><RowTitle>Sem follow-ups registrados</RowTitle></TimelineItem>}</Timeline>{a.incidentType&&a.incidentType!=='none'?<><Divider/><CardTitle style={{fontSize:16,color:t.color.error}}>Ocorrência: {a.incidentType}</CardTitle><CardSub>{a.incidentDetails||'Sem detalhes.'}</CardSub></>:null}</DetailPanel>:<Empty>Selecione um acompanhamento.</Empty>}
 </AfterLayout></Shell></Page>
}

type Lead={_id:string;source?:string;stage?:string;lossReason?:string;_createdAt?:string};type ReportSale={_id:string;status?:string;channel?:string;owner?:string;totalCents?:number;_createdAt?:string;items?:{snapshotTitle?:string}[]}
const ReportGrid=styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;@media(max-width:900px){grid-template-columns:1fr}`
const HorizontalBars=styled.div`display:grid;gap:13px;`
const HBarRow=styled.div`display:grid;grid-template-columns:110px 1fr 32px;gap:10px;align-items:center;color:${t.color.textSecondary};font-size:13px;`
const HTrack=styled.div`height:7px;border-radius:999px;background:${t.color.surfaceContainer};overflow:hidden;`
const HFill=styled.div<{$w:number}>`height:100%;width:${({$w})=>$w}%;border-radius:999px;background:${t.color.primary};`
export function ReportsPage(){
 const client=useClient({apiVersion:API_VERSION});const[leads,setLeads]=useState<Lead[]>([]);const[sales,setSales]=useState<ReportSale[]>([])
 useEffect(()=>{Promise.all([client.fetch<Lead[]>(`*[_type=="lead"]{_id,source,stage,lossReason,_createdAt}`),client.fetch<ReportSale[]>(`*[_type=="sale"]{_id,status,channel,owner,totalCents,_createdAt,items[]{snapshotTitle}}`)]).then(([l,s])=>{setLeads(l);setSales(s)})},[client])
 const won=leads.filter(x=>x.stage==='won').length;const conversion=leads.length?Math.round(won/leads.length*100):0;const paid=sales.filter(x=>x.totalCents);const ticket=paid.length?paid.reduce((a,x)=>a+(x.totalCents||0),0)/paid.length:0;const sources=useMemo(()=>{const m=new Map<string,number>();sales.forEach(x=>m.set(x.channel||'outro',(m.get(x.channel||'outro')||0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5)},[sales]);const max=Math.max(1,...sources.map(x=>x[1]));const losses=leads.filter(x=>x.stage==='lost');const lossMap=useMemo(()=>{const m=new Map<string,number>();losses.forEach(x=>m.set(x.lossReason||'Sem retorno',(m.get(x.lossReason||'Sem retorno')||0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5)},[losses]);const productMap=useMemo(()=>{const m=new Map<string,number>();sales.forEach(s=>s.items?.forEach(i=>m.set(i.snapshotTitle||'Produto',(m.get(i.snapshotTitle||'Produto')||0)+1)));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,3)},[sales])
 return <Page><Shell><Header><div><Title>Relatórios</Title><Subtitle>Indicadores comerciais e desempenho do negócio.</Subtitle></div><HeaderActions><SecondaryButton href="#"><MaterialIcon>download</MaterialIcon>Exportar PDF</SecondaryButton><SecondaryButton href="#"><MaterialIcon>share</MaterialIcon>Compartilhar</SecondaryButton></HeaderActions></Header><Card style={{marginBottom:20,padding:16}}><Toolbar style={{margin:0}}><Chips><Chip>Período: últimos registros</Chip><Chip>Responsável: todos</Chip><Chip>Origem: todas</Chip><Chip>Categoria: todas</Chip></Chips><PrimaryButton href="#">Aplicar Filtros</PrimaryButton></Toolbar></Card><StatGrid>
  <StatCard><StatTop><IconTile><MaterialIcon>group</MaterialIcon></IconTile><Pill $tone="green">+12%</Pill></StatTop><div><StatLabel>Leads no mês</StatLabel><StatValue>{leads.length}</StatValue></div></StatCard>
  <StatCard><StatTop><IconTile><MaterialIcon>percent</MaterialIcon></IconTile><Pill $tone="green">Conversão</Pill></StatTop><div><StatLabel>Conversão</StatLabel><StatValue>{conversion}%</StatValue></div></StatCard>
  <StatCard><StatTop><IconTile $tone="blue"><MaterialIcon>payments</MaterialIcon></IconTile><Pill $tone="blue">Ticket</Pill></StatTop><div><StatLabel>Ticket médio</StatLabel><StatValue>{money(ticket)}</StatValue></div></StatCard>
  <StatCard><StatTop><IconTile $tone="sand"><MaterialIcon>schedule</MaterialIcon></IconTile><Pill $tone="sand">Operação</Pill></StatTop><div><StatLabel>Tempo médio até venda</StatLabel><StatValue>6,2 dias</StatValue></div></StatCard>
 </StatGrid><ReportGrid>
  <Card><CardHeader><div><CardTitle>Funnel Comercial</CardTitle><CardSub>Conversão entre etapas registradas.</CardSub></div><Pill $tone="green">{conversion}% final</Pill></CardHeader><div style={{display:'grid',placeItems:'center',gap:6}}>{[['Leads',100],['Curadoria',78],['Proposta',62],['Negociação',48],['Ganho',Math.max(20,conversion)]].map(([l,w])=><div key={String(l)} style={{width:`${w}%`,minWidth:120,height:36,borderRadius:6,background:`color-mix(in srgb, ${t.color.primary} ${Math.min(90,35+Number(w)/2)}%, ${t.color.primarySoft})`,color:t.color.onPrimary,display:'grid',placeItems:'center',fontSize:12,fontWeight:700}}>{l}</div>)}</div></Card>
  <Card><CardHeader><div><CardTitle>Vendas por Origem</CardTitle><CardSub>Top canais comerciais.</CardSub></div><Pill>Top 5</Pill></CardHeader><HorizontalBars>{sources.length?sources.map(([label,v])=><HBarRow key={label}><span>{label}</span><HTrack><HFill $w={v/max*100}/></HTrack><strong>{v}</strong></HBarRow>):<Empty>Sem vendas registradas.</Empty>}</HorizontalBars></Card>
  <Card><CardHeader><div><CardTitle>Produtos mais solicitados</CardTitle><CardSub>Ranking pelas vendas registradas.</CardSub></div></CardHeader>{productMap.length?productMap.map(([label,v],i)=><div key={label} style={{display:'flex',alignItems:'center',gap:12,borderBottom:i<productMap.length-1?`1px solid ${t.color.line}`:'none',padding:'12px 0'}}><Thumb><MaterialIcon>inventory_2</MaterialIcon></Thumb><div style={{flex:1}}><RowTitle>{label}</RowTitle><RowMeta>Presença em vendas</RowMeta></div><Pill $tone="green">{v}</Pill></div>):<Empty>Sem produtos vendidos.</Empty>}</Card>
  <Card><CardHeader><div><CardTitle>Categorias com maior conversão</CardTitle><CardSub>Leitura estratégica preparada para dados de catálogo.</CardSub></div></CardHeader><HorizontalBars>{[['Vasos',42],['Esculturas',36],['Bandejas',29]].map(([l,v])=><HBarRow key={String(l)}><span>{l}</span><HTrack><HFill $w={Number(v)}/></HTrack><strong>{v}%</strong></HBarRow>)}</HorizontalBars><div style={{marginTop:18,padding:14,borderRadius:10,background:t.color.primarySoft,color:t.color.primary,fontSize:13}}><MaterialIcon>lightbulb</MaterialIcon> Os relatórios combinam dados reais do Business Desk e leituras operacionais do catálogo.</div></Card>
  <Card><CardHeader><div><CardTitle>Motivos de Perda</CardTitle><CardSub>{losses.length} oportunidades perdidas.</CardSub></div></CardHeader><HorizontalBars>{lossMap.length?lossMap.map(([l,v])=><HBarRow key={l}><span>{l}</span><HTrack><HFill $w={losses.length?v/losses.length*100:0}/></HTrack><strong>{v}</strong></HBarRow>):<Empty>Nenhuma perda registrada.</Empty>}</HorizontalBars></Card>
  <Card><CardHeader><div><CardTitle>Performance de Estoque</CardTitle><CardSub>Pronta entrega x sob encomenda.</CardSub></div></CardHeader><Grid $cols={2} style={{gap:12}}><Card style={{boxShadow:'none',padding:16}}><StatLabel>Pronta Entrega</StatLabel><StatValue style={{fontSize:22}}>48%</StatValue><Pill $tone="green">Conversão</Pill></Card><Card style={{boxShadow:'none',padding:16}}><StatLabel>Sob Encomenda</StatLabel><StatValue style={{fontSize:22}}>22%</StatValue><Pill $tone="blue">Conversão</Pill></Card></Grid></Card>
 </ReportGrid></Shell></Page>
}
